In [1]:
import numpy as np
import pandas as pd

In [2]:
employee1 = pd.Series({'Name' : 'Aditya', 'ID' : 1, 'Gender' : 'Male' , 'Salary' : 950000})
employee2 = pd.Series({'Name' : 'Rahul', 'ID' : 2, 'Gender' : 'Male' , 'Salary' : 750000})
employee3 = pd.Series({'Name' : 'Akash', 'ID' : 3, 'Gender' : 'Male' , 'Salary' : 750000})
employee4 = pd.Series({'Name' : 'rakesh', 'ID' : 4, 'Gender' : 'Male' , 'Salary' : 780000})
employee5 = pd.Series({'Name' : 'Monty', 'ID' : 5, 'Gender' : 'Male' , 'Salary' : 350000})
employee6 = pd.Series({'Name' : 'Abhishek', 'ID' : 6, 'Gender' : 'Male' , 'Salary' : 330000})
employee7 = pd.Series({'Name' : 'rekha', 'ID' : 7, 'Gender' : 'Female' , 'Salary' : 630000})
employee8 = pd.Series({'Name' : 'vaishnavi', 'ID' : 8, 'Gender' : 'Female' , 'Salary' : 670000})
employee9 = pd.Series({'Name' : 'Aditi', 'ID' : 9, 'Gender' : 'Female' , 'Salary' : 920000})
employee10 = pd.Series({'Name' : 'seema', 'ID' : 10, 'Gender' : 'Female' , 'Salary' : 750000})
employee11 = pd.Series({'Name' : 'reema', 'ID' : 11, 'Gender' : 'Female' , 'Salary' : 450000})
employee12 = pd.Series({'Name' : 'mohini', 'ID' : 12, 'Gender' : 'Female' , 'Salary' : 550000})
employee13 = pd.Series({'Name' : 'padmini', 'ID' : 13, 'Gender' : 'Female' , 'Salary' : 370000})
employee14 = pd.Series({'Name' : 'shital', 'ID' : 14, 'Gender' : 'Female' , 'Salary' : 670000})
employee15 = pd.Series({'Name' : 'munni', 'ID' : 15, 'Gender' : 'Female' , 'Salary' : 640000})

In [4]:
employees = [employee1, employee2, employee3, employee4, employee5, employee6, employee7, employee8, employee9, employee10, employee11, employee12, employee13, employee14, employee15 ]
employees

[Name      Aditya
 ID             1
 Gender      Male
 Salary    950000
 dtype: object,
 Name       Rahul
 ID             2
 Gender      Male
 Salary    750000
 dtype: object,
 Name       Akash
 ID             3
 Gender      Male
 Salary    750000
 dtype: object,
 Name      rakesh
 ID             4
 Gender      Male
 Salary    780000
 dtype: object,
 Name       Monty
 ID             5
 Gender      Male
 Salary    350000
 dtype: object,
 Name      Abhishek
 ID               6
 Gender        Male
 Salary      330000
 dtype: object,
 Name       rekha
 ID             7
 Gender    Female
 Salary    630000
 dtype: object,
 Name      vaishnavi
 ID                8
 Gender       Female
 Salary       670000
 dtype: object,
 Name       Aditi
 ID             9
 Gender    Female
 Salary    920000
 dtype: object,
 Name       seema
 ID            10
 Gender    Female
 Salary    750000
 dtype: object,
 Name       reema
 ID            11
 Gender    Female
 Salary    450000
 dtype: object,
 Name      mohini
 ID            12
 Gender    Female
 Salary    550000
 dtype: object,
 Name      padmini
 ID             13
 Gender     Female
 Salary     370000
 dtype: object,
 Name      shital
 ID            14
 Gender    Female
 Salary    670000
 dtype: object,
 Name       munni
 ID            15
 Gender    Female
 Salary    640000
 dtype: object]

In [7]:
employees.describe

AttributeError: 'list' object has no attribute 'describe'

In [8]:

df = pd.DataFrame(data = employees, index = range(101, 116))
df

          Name  ID  Gender  Salary
101     Aditya   1    Male  950000
102      Rahul   2    Male  750000
103      Akash   3    Male  750000
104     rakesh   4    Male  780000
105      Monty   5    Male  350000
106   Abhishek   6    Male  330000
107      rekha   7  Female  630000
108  vaishnavi   8  Female  670000
109      Aditi   9  Female  920000
110      seema  10  Female  750000
111      reema  11  Female  450000
112     mohini  12  Female  550000
113    padmini  13  Female  370000
114     shital  14  Female  670000
115      munni  15  Female  640000



> Add blockquote

In [10]:
# Information about dataframe
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15 entries, 101 to 115
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    15 non-null     object
 1   ID      15 non-null     int64
 2   Gender  15 non-null     object
 3   Salary  15 non-null     int64
dtypes: int64(2), object(2)
memory usage: 612.0+ bytes

In [11]:
#statistical info about df
df.describe()

              ID         Salary
count  15.000000      15.000000
mean    8.000000  637333.333333
std     4.472136  194476.097197
min     1.000000  330000.000000
25%     4.500000  500000.000000
50%     8.000000  670000.000000
75%    11.500000  750000.000000
max    15.000000  950000.000000

In [12]:
df.head(7)

         Name  ID  Gender  Salary
101    Aditya   1    Male  950000
102     Rahul   2    Male  750000
103     Akash   3    Male  750000
104    rakesh   4    Male  780000
105     Monty   5    Male  350000
106  Abhishek   6    Male  330000
107     rekha   7  Female  630000

In [13]:
df.tail(7)

        Name  ID  Gender  Salary
109    Aditi   9  Female  920000
110    seema  10  Female  750000
111    reema  11  Female  450000
112   mohini  12  Female  550000
113  padmini  13  Female  370000
114   shital  14  Female  670000
115    munni  15  Female  640000

In [14]:
df.values

# it gives values of dataframe

array([['Aditya', 1, 'Male', 950000],
       ['Rahul', 2, 'Male', 750000],
       ['Akash', 3, 'Male', 750000],
       ['rakesh', 4, 'Male', 780000],
       ['Monty', 5, 'Male', 350000],
       ['Abhishek', 6, 'Male', 330000],
       ['rekha', 7, 'Female', 630000],
       ['vaishnavi', 8, 'Female', 670000],
       ['Aditi', 9, 'Female', 920000],
       ['seema', 10, 'Female', 750000],
       ['reema', 11, 'Female', 450000],
       ['mohini', 12, 'Female', 550000],
       ['padmini', 13, 'Female', 370000],
       ['shital', 14, 'Female', 670000],
       ['munni', 15, 'Female', 640000]], dtype=object)

In [15]:
df.index
# it gives stars and stop index

RangeIndex(start=101, stop=116, step=1)

In [17]:
list(df.index)
# you can get index in list format

[101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115]

In [18]:
df.columns

Index(['Name', 'ID', 'Gender', 'Salary'], dtype='object')

In [20]:
df.name = "Employee_Details"
df.index.name = "Employee_ID"

In [22]:
df.name

'Employee_Details'

In [21]:
df.index.name

'Employee_ID'

Accessing data from DataFrame

In [33]:
df['Name']

Employee_ID
101       Aditya
102        Rahul
103        Akash
104       rakesh
105        Monty
106     Abhishek
107        rekha
108    vaishnavi
109        Aditi
110        seema
111        reema
112       mohini
113      padmini
114       shital
115        munni
Name: Name, dtype: object

In [34]:
df.Name

Employee_ID
101       Aditya
102        Rahul
103        Akash
104       rakesh
105        Monty
106     Abhishek
107        rekha
108    vaishnavi
109        Aditi
110        seema
111        reema
112       mohini
113      padmini
114       shital
115        munni
Name: Name, dtype: object

In [26]:
df[["Name", "Salary"]]

                  Name  Salary
Employee_ID
101             Aditya  950000
102              Rahul  750000
103              Akash  750000
104             rakesh  780000
105              Monty  350000
106           Abhishek  330000
107              rekha  630000
108          vaishnavi  670000
109              Aditi  920000
110              seema  750000
111              reema  450000
112             mohini  550000
113            padmini  370000
114             shital  670000
115              munni  640000

In [27]:
df[['Name' , 'Gender']]

                  Name  Gender
Employee_ID
101             Aditya    Male
102              Rahul    Male
103              Akash    Male
104             rakesh    Male
105              Monty    Male
106           Abhishek    Male
107              rekha  Female
108          vaishnavi  Female
109              Aditi  Female
110              seema  Female
111              reema  Female
112             mohini  Female
113            padmini  Female
114             shital  Female
115              munni  Female

In [28]:
df

                  Name  ID  Gender  Salary
Employee_ID
101             Aditya   1    Male  950000
102              Rahul   2    Male  750000
103              Akash   3    Male  750000
104             rakesh   4    Male  780000
105              Monty   5    Male  350000
106           Abhishek   6    Male  330000
107              rekha   7  Female  630000
108          vaishnavi   8  Female  670000
109              Aditi   9  Female  920000
110              seema  10  Female  750000
111              reema  11  Female  450000
112             mohini  12  Female  550000
113            padmini  13  Female  370000
114             shital  14  Female  670000
115              munni  15  Female  640000

Accessing either single of multiple Records

In [29]:
df.loc[101]

Name      Aditya
ID             1
Gender      Male
Salary    950000
Name: 101, dtype: object

In [30]:
df.iloc[8]

Name       Aditi
ID             9
Gender    Female
Salary    920000
Name: 109, dtype: object

In [31]:
df.loc[[101,104,115]]

               Name  ID  Gender  Salary
Employee_ID
101          Aditya   1    Male  950000
104          rakesh   4    Male  780000
115           munni  15  Female  640000

In [38]:
df.loc[105:108]

                  Name  ID  Gender  Salary
Employee_ID
105              Monty   5    Male  350000
106           Abhishek   6    Male  330000
107              rekha   7  Female  630000
108          vaishnavi   8  Female  670000

Accessing Spesefic value

In [ ]:
df.Name.loc[[101,104,115]]

Employee_ID
101    Aditya
104    rakesh
115     munni
Name: Name, dtype: object

In [ ]:
df.loc[105]['Salary']

np.int64(350000)

In [ ]:
df.loc[111]['Name']

'reema'

In [ ]:
df.loc[[109]] [['Name','Gender']]

              Name  Gender
Employee_ID
109          Aditi  Female

In [ ]:
df.loc[101:112:2]

               Name  ID  Gender  Salary
Employee_ID
101          Aditya   1    Male  950000
103           Akash   3    Male  750000
105           Monty   5    Male  350000
107           rekha   7  Female  630000
109           Aditi   9  Female  920000
111           reema  11  Female  450000

In [45]:
df.loc[101:112:2, ['Name' , 'Gender']]

               Name  Gender
Employee_ID
101          Aditya    Male
103           Akash    Male
105           Monty    Male
107           rekha  Female
109           Aditi  Female
111           reema  Female

In [52]:
df.loc[df["Gender"] == "Female"]

                  Name  ID  Gender  Salary
Employee_ID
107              rekha   7  Female  630000
108          vaishnavi   8  Female  670000
109              Aditi   9  Female  920000
110              seema  10  Female  750000
111              reema  11  Female  450000
112             mohini  12  Female  550000
113            padmini  13  Female  370000
114             shital  14  Female  670000
115              munni  15  Female  640000

In [51]:
df[df.Gender == "Male"]

                 Name  ID Gender  Salary
Employee_ID
101            Aditya   1   Male  950000
102             Rahul   2   Male  750000
103             Akash   3   Male  750000
104            rakesh   4   Male  780000
105             Monty   5   Male  350000
106          Abhishek   6   Male  330000

In [62]:
df[df.Gender == "Female"] [df.Salary >= 80000]

/tmp/ipython-input-2082786973.py:1: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  df[df.Gender == "Female"] [df.Salary >= 80000]

                  Name  ID  Gender  Salary
Employee_ID
107              rekha   7  Female  630000
108          vaishnavi   8  Female  670000
109              Aditi   9  Female  920000
110              seema  10  Female  750000
111              reema  11  Female  450000
112             mohini  12  Female  550000
113            padmini  13  Female  370000
114             shital  14  Female  670000
115              munni  15  Female  640000

In [63]:
df.loc[105,["Salary"]]

Salary    350000
Name: 105, dtype: object

Adding Deleting Rows and Coloumns

In [58]:
df

                  Name  ID  Gender  Salary
Employee_ID
101             Aditya   1    Male  950000
102              Rahul   2    Male  750000
103              Akash   3    Male  750000
104             rakesh   4    Male  780000
105              Monty   5    Male  350000
106           Abhishek   6    Male  330000
107              rekha   7  Female  630000
108          vaishnavi   8  Female  670000
109              Aditi   9  Female  920000
110              seema  10  Female  750000
111              reema  11  Female  450000
112             mohini  12  Female  550000
113            padmini  13  Female  370000
114             shital  14  Female  670000
115              munni  15  Female  640000

In [64]:
df.loc[116] = ["Rasika", 16, "Female", 905555]
df

                  Name  ID  Gender  Salary
Employee_ID
101             Aditya   1    Male  950000
102              Rahul   2    Male  750000
103              Akash   3    Male  750000
104             rakesh   4    Male  780000
105              Monty   5    Male  350000
106           Abhishek   6    Male  330000
107              rekha   7  Female  630000
108          vaishnavi   8  Female  670000
109              Aditi   9  Female  920000
110              seema  10  Female  750000
111              reema  11  Female  450000
112             mohini  12  Female  550000
113            padmini  13  Female  370000
114             shital  14  Female  670000
115              munni  15  Female  640000
116             Rasika  16  Female  905555

In [69]:
df.loc[103] =["Sam",3, "Male", 450000 ]
df

                  Name  ID  Gender  Salary
Employee_ID
101             Aditya   1    Male  950000
102              Rahul   2    Male  750000
103                Sam   3    Male  450000
104             rakesh   4    Male  780000
105              Monty   5    Male  350000
106           Abhishek   6    Male  330000
107              rekha   7  Female  630000
108          vaishnavi   8  Female  670000
109              Aditi   9  Female  920000
110              seema  10  Female  750000
111              reema  11  Female  450000
112             mohini  12  Female  550000
113            padmini  13  Female  370000
114             shital  14  Female  670000
115              munni  15  Female  640000
116             Rasika  16  Female  905555

In [72]:
df.drop(116, inplace = True, axis = 0)

KeyError: '[116] not found in axis'

In [73]:
df

                  Name  ID  Gender  Salary
Employee_ID
101             Aditya   1    Male  950000
102              Rahul   2    Male  750000
103                Sam   3    Male  450000
104             rakesh   4    Male  780000
105              Monty   5    Male  350000
106           Abhishek   6    Male  330000
107              rekha   7  Female  630000
108          vaishnavi   8  Female  670000
109              Aditi   9  Female  920000
110              seema  10  Female  750000
111              reema  11  Female  450000
112             mohini  12  Female  550000
113            padmini  13  Female  370000
114             shital  14  Female  670000
115              munni  15  Female  640000

In [75]:
df["City"] = "Nashik"
df

                  Name  ID  Gender  Salary    City
Employee_ID
101             Aditya   1    Male  950000  Nashik
102              Rahul   2    Male  750000  Nashik
103                Sam   3    Male  450000  Nashik
104             rakesh   4    Male  780000  Nashik
105              Monty   5    Male  350000  Nashik
106           Abhishek   6    Male  330000  Nashik
107              rekha   7  Female  630000  Nashik
108          vaishnavi   8  Female  670000  Nashik
109              Aditi   9  Female  920000  Nashik
110              seema  10  Female  750000  Nashik
111              reema  11  Female  450000  Nashik
112             mohini  12  Female  550000  Nashik
113            padmini  13  Female  370000  Nashik
114             shital  14  Female  670000  Nashik
115              munni  15  Female  640000  Nashik

In [77]:
df.drop("City", inplace= True, axis = 1)
df

                  Name  ID  Gender  Salary
Employee_ID
101             Aditya   1    Male  950000
102              Rahul   2    Male  750000
103                Sam   3    Male  450000
104             rakesh   4    Male  780000
105              Monty   5    Male  350000
106           Abhishek   6    Male  330000
107              rekha   7  Female  630000
108          vaishnavi   8  Female  670000
109              Aditi   9  Female  920000
110              seema  10  Female  750000
111              reema  11  Female  450000
112             mohini  12  Female  550000
113            padmini  13  Female  370000
114             shital  14  Female  670000
115              munni  15  Female  640000

In [79]:
df['Age'] = np.random.randint(20,40,15)
df

                  Name  ID  Gender  Salary  Age
Employee_ID
101             Aditya   1    Male  950000   26
102              Rahul   2    Male  750000   37
103                Sam   3    Male  450000   21
104             rakesh   4    Male  780000   20
105              Monty   5    Male  350000   39
106           Abhishek   6    Male  330000   27
107              rekha   7  Female  630000   36
108          vaishnavi   8  Female  670000   36
109              Aditi   9  Female  920000   33
110              seema  10  Female  750000   32
111              reema  11  Female  450000   21
112             mohini  12  Female  550000   23
113            padmini  13  Female  370000   21
114             shital  14  Female  670000   26
115              munni  15  Female  640000   31

In [ ]:
df.drop(116, inplace= True, axis = 0)
df
# axix 0 = row | axis 1 =  Column

                  Name  ID  Gender  Salary  Age
Employee_ID
101             Aditya   1    Male  950000   31
102              Rahul   2    Male  750000   28
103              Akash   3    Male  750000   29
104             rakesh   4    Male  780000   29
105              Monty   5    Male  350000   25
106           Abhishek   6    Male  330000   38
107              rekha   7  Female  630000   20
108          vaishnavi   8  Female  670000   31
109              Aditi   9  Female  920000   39
110              seema  10  Female  750000   29
111              reema  11  Female  450000   29
112             mohini  12  Female  550000   22
114             shital  14  Female  670000   27
115              munni  15  Female  640000   34

In [91]:

df[df.Gender == "Female"] [df.Age >= 25]

/tmp/ipython-input-1065344673.py:1: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  df[df.Gender == "Female"] [df.Age >= 25]

                  Name  ID  Gender  Salary  Age
Employee_ID
107              rekha   7  Female  630000   36
108          vaishnavi   8  Female  670000   36
109              Aditi   9  Female  920000   33
110              seema  10  Female  750000   32
114             shital  14  Female  670000   26
115              munni  15  Female  640000   31

In [ ]:
df.drop(112, inplace= True, axis = 0)
df
# axix 0 = row | axis 1 =  Column

                  Name  ID  Gender  Salary  Age
Employee_ID
101             Aditya   1    Male  950000   31
102              Rahul   2    Male  750000   28
103              Akash   3    Male  750000   29
104             rakesh   4    Male  780000   29
105              Monty   5    Male  350000   25
106           Abhishek   6    Male  330000   38
107              rekha   7  Female  630000   20
108          vaishnavi   8  Female  670000   31
109              Aditi   9  Female  920000   39
110              seema  10  Female  750000   29
111              reema  11  Female  450000   29
114             shital  14  Female  670000   27
115              munni  15  Female  640000   34

In [ ]:
df["City"] = "Nashik"
df

                  Name  ID  Gender  Salary    City
Employee_ID
101             Aditya   1    Male  950000  Nashik
102              Rahul   2    Male  750000  Nashik
103              Akash   3    Male  750000  Nashik
104             rakesh   4    Male  780000  Nashik
105              Monty   5    Male  350000  Nashik
106           Abhishek   6    Male  330000  Nashik
107              rekha   7  Female  630000  Nashik
108          vaishnavi   8  Female  670000  Nashik
109              Aditi   9  Female  920000  Nashik
110              seema  10  Female  750000  Nashik
111              reema  11  Female  450000  Nashik
112             mohini  12  Female  550000  Nashik
113            padmini  13  Female  370000  Nashik
114             shital  14  Female  670000  Nashik
115              munni  15  Female  640000  Nashik

In [ ]:
df.drop("Age", inplace= True, axis = 1)
df
#delete the coloumn with axis 1

                  Name  ID  Gender  Salary    City
Employee_ID
101             Aditya   1    Male  950000  Nashik
102              Rahul   2    Male  750000  Nashik
103              Akash   3    Male  750000  Nashik
104             rakesh   4    Male  780000  Nashik
105              Monty   5    Male  350000  Nashik
106           Abhishek   6    Male  330000  Nashik
107              rekha   7  Female  630000  Nashik
108          vaishnavi   8  Female  670000  Nashik
109              Aditi   9  Female  920000  Nashik
110              seema  10  Female  750000  Nashik
111              reema  11  Female  450000  Nashik
114             shital  14  Female  670000  Nashik
115              munni  15  Female  640000  Nashik

In [ ]:
df.loc[105] = ["shubham", 5, "Male", 50000, "Nashik"]

ValueError: Must have equal len keys and value when setting with an iterable

Queary based on condition

In [ ]:
df['Age'] = np.random.randint(20,40,15)
df

                  Name  ID  Gender  Salary    City  Age
Employee_ID
101             Aditya   1    Male  950000  Nashik   23
102              Rahul   2    Male  750000  Nashik   21
103              Akash   3    Male  750000  Nashik   24
104             rakesh   4    Male  780000  Nashik   35
105              Monty   5    Male  350000  Nashik   39
106           Abhishek   6    Male  330000  Nashik   38
107              rekha   7  Female  630000  Nashik   33
108          vaishnavi   8  Female  670000  Nashik   35
109              Aditi   9  Female  920000  Nashik   20
110              seema  10  Female  750000  Nashik   35
111              reema  11  Female  450000  Nashik   28
112             mohini  12  Female  550000  Nashik   31
113            padmini  13  Female  370000  Nashik   35
114             shital  14  Female  670000  Nashik   32
115              munni  15  Female  640000  Nashik   29

In [ ]:
df[df.Salary > 850000][['Name', 'Age']]

               Name  Age
Employee_ID
101          Aditya   23
109           Aditi   20

In [ ]:
df[df.Gender == "Female"] [df.Salary < 600000 ] ["ID"]

/tmp/ipython-input-1143116632.py:1: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  df[df.Gender == "Female"] [df.Salary < 600000 ] ["ID"]

Employee_ID
111    11
112    12
113    13
Name: ID, dtype: int64

In [ ]:
df.query('Salary > 850000')

               Name  ID  Gender  Salary    City  Age
Employee_ID
101          Aditya   1    Male  950000  Nashik   23
109           Aditi   9  Female  920000  Nashik   20

In [ ]:
df.query('Gender == "Female"')

                  Name  ID  Gender  Salary    City  Age
Employee_ID
107              rekha   7  Female  630000  Nashik   33
108          vaishnavi   8  Female  670000  Nashik   35
109              Aditi   9  Female  920000  Nashik   20
110              seema  10  Female  750000  Nashik   35
111              reema  11  Female  450000  Nashik   28
112             mohini  12  Female  550000  Nashik   31
113            padmini  13  Female  370000  Nashik   35
114             shital  14  Female  670000  Nashik   32
115              munni  15  Female  640000  Nashik   29

In [ ]:
df.query('Gender == "Female" and Salary < 600000')

                Name  ID  Gender  Salary    City  Age
Employee_ID
111            reema  11  Female  450000  Nashik   28
112           mohini  12  Female  550000  Nashik   31
113          padmini  13  Female  370000  Nashik   35

In [ ]:
df.query('Salary > 600000 and Salary < 900000')

                  Name  ID  Gender  Salary    City  Age
Employee_ID
102              Rahul   2    Male  750000  Nashik   21
103              Akash   3    Male  750000  Nashik   24
104             rakesh   4    Male  780000  Nashik   35
107              rekha   7  Female  630000  Nashik   33
108          vaishnavi   8  Female  670000  Nashik   35
110              seema  10  Female  750000  Nashik   35
114             shital  14  Female  670000  Nashik   32
115              munni  15  Female  640000  Nashik   29

# **Important function**

In [ ]:
# to show all the data
df

                  Name  ID  Gender  Salary    City  Age
Employee_ID
101             Aditya   1    Male  950000  Nashik   23
102              Rahul   2    Male  750000  Nashik   21
103              Akash   3    Male  750000  Nashik   24
104             rakesh   4    Male  780000  Nashik   35
105              Monty   5    Male  350000  Nashik   39
106           Abhishek   6    Male  330000  Nashik   38
107              rekha   7  Female  630000  Nashik   33
108          vaishnavi   8  Female  670000  Nashik   35
109              Aditi   9  Female  920000  Nashik   20
110              seema  10  Female  750000  Nashik   35
111              reema  11  Female  450000  Nashik   28
112             mohini  12  Female  550000  Nashik   31
113            padmini  13  Female  370000  Nashik   35
114             shital  14  Female  670000  Nashik   32
115              munni  15  Female  640000  Nashik   29

In [ ]:
# create duplicate date
# nan = not a  number
df.loc[116] = df.loc[107]
df.loc[117] = df.loc[103]
df.loc[118] = ["monjulika" , 15, np.nan, np.nan ,"Pune", 30]
df.loc[119] = ["vidya" , 16, np.nan, np.nan ,"Mumbai" ,34]
df

                  Name  ID  Gender    Salary    City  Age
Employee_ID
101             Aditya   1    Male  950000.0  Nashik   23
102              Rahul   2    Male  750000.0  Nashik   21
103              Akash   3    Male  750000.0  Nashik   24
104             rakesh   4    Male  780000.0  Nashik   35
105              Monty   5    Male  350000.0  Nashik   39
106           Abhishek   6    Male  330000.0  Nashik   38
107              rekha   7  Female  630000.0  Nashik   33
108          vaishnavi   8  Female  670000.0  Nashik   35
109              Aditi   9  Female  920000.0  Nashik   20
110              seema  10  Female  750000.0  Nashik   35
111              reema  11  Female  450000.0  Nashik   28
112             mohini  12  Female  550000.0  Nashik   31
113            padmini  13  Female  370000.0  Nashik   35
114             shital  14  Female  670000.0  Nashik   32
115              munni  15  Female  640000.0  Nashik   29
116              rekha   7  Female  630000.0  Nashik   33
117              Akash   3    Male  750000.0  Nashik   24
118          monjulika  15     NaN       NaN    Pune   30
119              vidya  16     NaN       NaN  Mumbai   34

In [ ]:
df.isnull().sum()

Name      0
ID        0
Gender    2
Salary    2
City      0
Age       0
dtype: int64

In [ ]:
df.duplicated().sum()

np.int64(2)

In [ ]:
df.drop_duplicates(inplace = True)
df

                  Name  ID  Gender    Salary    City  Age
Employee_ID
101             Aditya   1    Male  950000.0  Nashik   23
102              Rahul   2    Male  750000.0  Nashik   21
103              Akash   3    Male  750000.0  Nashik   24
104             rakesh   4    Male  780000.0  Nashik   35
105              Monty   5    Male  350000.0  Nashik   39
106           Abhishek   6    Male  330000.0  Nashik   38
107              rekha   7  Female  630000.0  Nashik   33
108          vaishnavi   8  Female  670000.0  Nashik   35
109              Aditi   9  Female  920000.0  Nashik   20
110              seema  10  Female  750000.0  Nashik   35
111              reema  11  Female  450000.0  Nashik   28
112             mohini  12  Female  550000.0  Nashik   31
113            padmini  13  Female  370000.0  Nashik   35
114             shital  14  Female  670000.0  Nashik   32
115              munni  15  Female  640000.0  Nashik   29
118          monjulika  15     NaN       NaN    Pune   30
119              vidya  16     NaN       NaN  Mumbai   34

In [ ]:
df.nunique()

Name      17
ID        16
Gender     2
Salary    12
City       3
Age       14
dtype: int64

In [ ]:
df["Name"].unique()

array(['Aditya', 'Rahul', 'Akash', 'rakesh', 'Monty', 'Abhishek', 'rekha',
       'vaishnavi', 'Aditi', 'seema', 'reema', 'mohini', 'padmini',
       'shital', 'munni', 'monjulika', 'vidya'], dtype=object)

In [ ]:
df['Gender'].unique()

array(['Male', 'Female', nan], dtype=object)

In [ ]:
df['Gender'].dropna().unique()

array(['Male', 'Female'], dtype=object)

In [ ]:
df.sort_index(ascending= True)

                  Name  ID  Gender    Salary    City  Age
Employee_ID
101             Aditya   1    Male  950000.0  Nashik   23
102              Rahul   2    Male  750000.0  Nashik   21
103              Akash   3    Male  750000.0  Nashik   24
104             rakesh   4    Male  780000.0  Nashik   35
105              Monty   5    Male  350000.0  Nashik   39
106           Abhishek   6    Male  330000.0  Nashik   38
107              rekha   7  Female  630000.0  Nashik   33
108          vaishnavi   8  Female  670000.0  Nashik   35
109              Aditi   9  Female  920000.0  Nashik   20
110              seema  10  Female  750000.0  Nashik   35
111              reema  11  Female  450000.0  Nashik   28
112             mohini  12  Female  550000.0  Nashik   31
113            padmini  13  Female  370000.0  Nashik   35
114             shital  14  Female  670000.0  Nashik   32
115              munni  15  Female  640000.0  Nashik   29
118          monjulika  15     NaN       NaN    Pune   30
119              vidya  16     NaN       NaN  Mumbai   34

In [ ]:
df.sort_index(ascending= False)

                  Name  ID  Gender    Salary    City  Age
Employee_ID
119              vidya  16     NaN       NaN  Mumbai   34
118          monjulika  15     NaN       NaN    Pune   30
115              munni  15  Female  640000.0  Nashik   29
114             shital  14  Female  670000.0  Nashik   32
113            padmini  13  Female  370000.0  Nashik   35
112             mohini  12  Female  550000.0  Nashik   31
111              reema  11  Female  450000.0  Nashik   28
110              seema  10  Female  750000.0  Nashik   35
109              Aditi   9  Female  920000.0  Nashik   20
108          vaishnavi   8  Female  670000.0  Nashik   35
107              rekha   7  Female  630000.0  Nashik   33
106           Abhishek   6    Male  330000.0  Nashik   38
105              Monty   5    Male  350000.0  Nashik   39
104             rakesh   4    Male  780000.0  Nashik   35
103              Akash   3    Male  750000.0  Nashik   24
102              Rahul   2    Male  750000.0  Nashik   21
101             Aditya   1    Male  950000.0  Nashik   23

display top 5 employees who were having maximum salaries

In [ ]:
df.sort_values(by = 'Salary' , ascending = False).head(5)

               Name  ID  Gender    Salary    City  Age
Employee_ID
101          Aditya   1    Male  950000.0  Nashik   23
109           Aditi   9  Female  920000.0  Nashik   20
104          rakesh   4    Male  780000.0  Nashik   35
103           Akash   3    Male  750000.0  Nashik   24
102           Rahul   2    Male  750000.0  Nashik   21

In [ ]:
pd.concat([df, df], axis = 0)

                  Name  ID  Gender    Salary    City  Age
Employee_ID
101             Aditya   1    Male  950000.0  Nashik   23
102              Rahul   2    Male  750000.0  Nashik   21
103              Akash   3    Male  750000.0  Nashik   24
104             rakesh   4    Male  780000.0  Nashik   35
105              Monty   5    Male  350000.0  Nashik   39
106           Abhishek   6    Male  330000.0  Nashik   38
107              rekha   7  Female  630000.0  Nashik   33
108          vaishnavi   8  Female  670000.0  Nashik   35
109              Aditi   9  Female  920000.0  Nashik   20
110              seema  10  Female  750000.0  Nashik   35
111              reema  11  Female  450000.0  Nashik   28
112             mohini  12  Female  550000.0  Nashik   31
113            padmini  13  Female  370000.0  Nashik   35
114             shital  14  Female  670000.0  Nashik   32
115              munni  15  Female  640000.0  Nashik   29
118          monjulika  15     NaN       NaN    Pune   30
119              vidya  16     NaN       NaN  Mumbai   34
101             Aditya   1    Male  950000.0  Nashik   23
102              Rahul   2    Male  750000.0  Nashik   21
103              Akash   3    Male  750000.0  Nashik   24
104             rakesh   4    Male  780000.0  Nashik   35
105              Monty   5    Male  350000.0  Nashik   39
106           Abhishek   6    Male  330000.0  Nashik   38
107              rekha   7  Female  630000.0  Nashik   33
108          vaishnavi   8  Female  670000.0  Nashik   35
109              Aditi   9  Female  920000.0  Nashik   20
110              seema  10  Female  750000.0  Nashik   35
111              reema  11  Female  450000.0  Nashik   28
112             mohini  12  Female  550000.0  Nashik   31
113            padmini  13  Female  370000.0  Nashik   35
114             shital  14  Female  670000.0  Nashik   32
115              munni  15  Female  640000.0  Nashik   29
118          monjulika  15     NaN       NaN    Pune   30
119              vidya  16     NaN       NaN  Mumbai   34

In [ ]:
pd.concat([df, df], axis = 1)

,Name,ID,Gender,Salary,City,Age,Name,ID,Gender,Salary,City,Age
Employee_ID,,,,,,,,,,,,
101,Aditya,1,Male,950000.0,Nashik,23,Aditya,1,Male,950000.0,Nashik,23
102,Rahul,2,Male,750000.0,Nashik,21,Rahul,2,Male,750000.0,Nashik,21
103,Akash,3,Male,750000.0,Nashik,24,Akash,3,Male,750000.0,Nashik,24
104,rakesh,4,Male,780000.0,Nashik,35,rakesh,4,Male,780000.0,Nashik,35
105,Monty,5,Male,350000.0,Nashik,39,Monty,5,Male,350000.0,Nashik,39
106,Abhishek,6,Male,330000.0,Nashik,38,Abhishek,6,Male,330000.0,Nashik,38
107,rekha,7,Female,630000.0,Nashik,33,rekha,7,Female,630000.0,Nashik,33
108,vaishnavi,8,Female,670000.0,Nashik,35,vaishnavi,8,Female,670000.0,Nashik,35
109,Aditi,9,Female,920000.0,Nashik,20,Aditi,9,Female,920000.0,Nashik,20
110,seema,10,Female,750000.0,Nashik,35,seema,10,Female,750000.0,Nashik,35
111,reema,11,Female,450000.0,Nashik,28,reema,11,Female,450000.0,Nashik,28
112,mohini,12,Female,550000.0,Nashik,31,mohini,12,Female,550000.0,Nashik,31
113,padmini,13,Female,370000.0,Nashik,35,padmini,13,Female,370000.0,Nashik,35
114,shital,14,Female,670000.0,Nashik,32,shital,14,Female,670000.0,Nashik,32
115,munni,15,Female,640000.0,Nashik,29,munni,15,Female,640000.0,Nashik,29
118,monjulika,15,NaN,NaN,Pune,30,monjulika,15,NaN,NaN,Pune,30
119,vidya,16,NaN,NaN,Mumbai,34,vidya,16,NaN,NaN,Mumbai,34

In [ ]:
# Statistical information about your df
df.describe()

              ID         Salary        Age
count  17.000000      15.000000  17.000000
mean    8.882353  637333.333333  30.705882
std     4.871888  194476.097197   5.796170
min     1.000000  330000.000000  20.000000
25%     5.000000  500000.000000  28.000000
50%     9.000000  670000.000000  32.000000
75%    13.000000  750000.000000  35.000000
max    16.000000  950000.000000  39.000000